"""Path roots for the v3 engine. Import this before anything else in a v3 script.

    v3/            this package: kernel_fast/, sanos/, diagnostics/, figures/
    <repo>/data/   the v2 loaders and targets the v3 engine still imports
    SANOS_V3_DATA  where fits, caches, panel records and the frozen static layer live

The third is deliberately NOT in the repository. It holds calibration OUTPUT -- per-date fit records,
the SANOS LP cache, the frozen static layer, panel records -- derived from licensed ORATS data and
regenerated by running the pipeline, not shipped with it. It defaults to `v3_data/` beside this
package and is overridden with the `SANOS_V3_DATA` environment variable, mirroring the
`ORATS_EOD_DIR` convention the loaders in `data/` already use (see the README's Data section).
"""
import os
import sys

V3 = os.path.dirname(os.path.abspath(__file__))            # <repo>/v3
ROOT = os.path.dirname(V3)                                 # <repo>
DATA = os.environ.get("SANOS_V3_DATA", os.path.join(ROOT, "v3_data"))
FIGS = os.environ.get("SANOS_V3_FIGS", os.path.join(DATA, "figs"))

# Code dirs first, DATA last: a stale duplicate left beside the outputs must never shadow a module.
for _p in (os.path.join(V3, "sanos"), os.path.join(V3, "kernel_fast"),
           os.path.join(V3, "diagnostics"), os.path.join(V3, "figures"),
           os.path.join(ROOT, "data"), os.path.join(ROOT, "poc"), DATA):
    if _p not in sys.path:
        sys.path.append(_p)
for _p in (os.path.join(V3, "sanos"), os.path.join(V3, "kernel_fast")):
    if _p in sys.path:
        sys.path.remove(_p)
    sys.path.insert(0, _p)
