#!/usr/bin/env python3
"""Emit the compact 7-free Jacobian table from `jacobian_7free_ALL.json`.

The spectrum is quoted in three places in the paper (the identifiability discussion of
Section 5.5, the limits of Section 6, and the soft-direction remark in the equivalence-class
paragraph). Appendix C, which used to hold the full per-date decomposition, was cut; this is the
compact replacement, generated from the artifact so the numbers cannot drift from it.

Reads:  vix_joint_refit/jacobian_7free_ALL.json
Writes: manuscript_v3/jacobian_table.tex   (a bare tabular; the paper wraps it in a table float)

The effective rank is the number of singular values above 1e-2 * s_max, the same tolerance the
artifact's own `eff` summary uses -- checked here rather than assumed.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
# Resolve through `_paths` rather than deriving a tree layout here: this file ships in the source
# tree, in the public repo and in the replication bundle, and those put the artifacts in three
# different places. `_paths` knows which one it is in; a hardcoded "../../vix_joint_refit" does not.
sys.path.insert(0, os.path.dirname(HERE))
import _paths as _P                                                   # noqa: E402
SRC = os.path.join(_P.DATA, "jacobian_7free_ALL.json")
# The manuscript \input{}s this next to its .tex, so prefer that directory where it exists;
# in the repo and the bundle there is no manuscript source tree and _P.FIGS is the output root.
_MS = os.path.join(ROOT, "manuscript_v3")
OUT = os.path.join(_MS if os.path.isdir(_MS) else _P.FIGS, "jacobian_table.tex")
TOL = 1e-2

TEX = {"nu_f": r"$\nu_{\mathsf F}$", "nu_s": r"$\nu_{\mathsf S}$", "nu_l": r"$\nu_{\mathsf L}$",
       "lam_skew": r"$\lambda_{\mathrm{skew}}$", "rho_f": r"$\rho_{\mathsf F}$",
       "kap_f": r"$\kappa_{\mathsf F}$", "kap_s": r"$\kappa_{\mathsf S}$"}
STAGE = {"_n9": "cold", "_dw9": "warm"}


def main():
    a = json.load(open(SRC))
    free, dates = a["free"], a["dates"]
    rows, effs, conds, smins = [], [], [], []
    for d in sorted(dates):
        r = dates[d]
        s = r["s7"]
        eff = sum(1 for x in s if x > TOL * s[0])
        cond = s[0] / s[-1]
        effs.append(eff), conds.append(cond), smins.append(s[-1])
        rows.append((d[:4], STAGE.get(r["tag"], r["tag"]), r["n_R"], s[0], s[-1], cond, eff))

    # the artifact carries [min, max, median] summaries; regenerate and check rather than trust
    def mmm(v):
        v = sorted(v)
        return [v[0], v[-1], v[len(v) // 2]]
    for k, got in (("eff", mmm(effs)), ("cond", mmm(conds)), ("smin", mmm(smins))):
        want = a[k]
        if any(abs(x - y) > 1e-6 * max(1.0, abs(y)) for x, y in zip(got, want)):
            sys.exit(f"{k}: regenerated {got} != artifact {want} -- tolerance or convention changed")

    soft = a["mean_soft_loading"]
    order = sorted(free, key=lambda p: -soft[p])

    L = [r"\begin{tabular}{llrrrrr}", r"\toprule",
         r"Year & stage & $d_{\Rcal}$ & $s_{\max}$ & $s_{\min}$ & $s_{\max}/s_{\min}$ & rank$_{10^{-2}}$ \\",
         r"\midrule"]
    for y, st, nr, smax, smin, cond, eff in rows:
        L.append(f"{y} & {st} & {nr} & ${smax:.1f}$ & ${smin:.4f}$ & ${cond:.0f}$ & ${eff}$ \\\\")
    L += [r"\midrule",
          r"\multicolumn{3}{l}{median} & & $%.4f$ & $%.0f$ & $%d$ \\" % (mmm(smins)[2], mmm(conds)[2], mmm(effs)[2]),
          r"\bottomrule", r"\end{tabular}",
          r"", r"\smallskip", r"",
          r"\begin{tabular}{l" + "r" * len(order) + "}",
          r"\toprule",
          r"mean loading on the softest direction & " + " & ".join(TEX[p] for p in order) + r" \\",
          r"\midrule",
          r"& " + " & ".join(f"${soft[p]:.3f}$" for p in order) + r" \\",
          r"\bottomrule", r"\end{tabular}"]

    with open(OUT, "w") as f:
        f.write("% generated by v3_scripts/diagnostics/emit_jacobian_table.py -- do not edit\n")
        f.write("\n".join(L) + "\n")
    print(f"wrote {OUT}")
    print(f"  softest {order[0]} ({soft[order[0]]:.3f})   stiffest {order[-1]} ({soft[order[-1]]:.3f})")
    print(f"  cond min/max/median {mmm(conds)[0]:.0f}/{mmm(conds)[1]:.0f}/{mmm(conds)[2]:.0f}"
          f"   rank min/max/median {mmm(effs)[0]}/{mmm(effs)[1]}/{mmm(effs)[2]}")


if __name__ == "__main__":
    main()
